function initLevel() {
    return new Level(
        [
            new Endboss(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new Chicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
            new SmallChicken(),
        ],
        [
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
            new Cloud(),
        ],
        [
            new BackgroundObject('img/5_background/layers/air.png', -719),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719),

            new BackgroundObject('img/5_background/layers/air.png', 0),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),

            new BackgroundObject('img/5_background/layers/air.png', 719),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719),

            new BackgroundObject('img/5_background/layers/air.png', 1438),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 1438),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 1438),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 1438),

            new BackgroundObject('img/5_background/layers/air.png', 2157),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 2157),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 2157),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 2157),

            new BackgroundObject('img/5_background/layers/air.png', 2876),
            new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 2876),
            new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 2876),
            new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 2876),

            new BackgroundObject('img/5_background/layers/air.png', 3595),
            new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 3595),
            new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 3595),
            new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 3595),
        ],
        [
            new Coin(500, 70),
            new Coin(1000, 70),
            new Coin(1500, 70),
            new Coin(2000, 70),
            new Coin(2500, 70),
            new Bottle(750, 330),
            new Bottle(1000, 330),
            new Bottle(1250, 330),
            new Bottle(1750, 330),
            new Bottle(2000, 330),
            new Bottle(2250, 330),
            new Bottle(2500, 330),
            new Bottle(2750, 330),
        ]
    );
}
